### ISSUE TITLE
Cannot read property "settings" of undefined

### ISSUE THREAD

**Issue by kirstylmarks** [tasuk/masonry-ordered#6]
Hi there.

I have this issue in my console, and its not laying out. I've added the settings and loaded masonry, so im unsure as to what the issue could be, and there is nothing on google.

Please can you help?

Thanks
Kirsty

**Comment by tasuki** [comment]
Kirsty, you need some kind of an ancient version of jQuery Masonry for this extension to work. It should work with `2.1.05`. Also, without knowing which `undefined` we're trying to read the property `settings` off of, it's hard to say for sure what the problem is!

**Comment by rusticblonde** [comment]
Hi Tasuki, apologies i thought i had put further detail.

I have put a screenshot of the error from the console.

Also, I will look at loading a seperate jQuery should it not work with newer versions.


![image](https://user-images.githubusercontent.com/2578920/52538126-b9e1ae00-2d66-11e9-9355-445f6e41e431.png)

**Comment by rusticblonde** [comment]
Hi Tasuki,

It appears during the newer versions of Masonry that a left to right horizontal order has been implemented. So i have just removed this. 

Thankyou anyways.
